title: Paul F Dennis # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Professorial Research Fellow | School of Environmental Sciences | University of East Anglia | Norwich NR4 7TJ | UK 
  <br><br>
  p(dot)dennis(at)uea(dot)ac(dot)uk 
  <br><br>
  I am an isotope geochemist and geologist, interested in the application of novel isotope techniques, notably clumped isotopes, for the detemination of (i) Earth surface palaeotemperatures, and (ii) fluid processes in the upper crust. 
  <br><br>
  This website is an openlaboratory manual documenting the concept, design, construction and performance of the MIRA stable isotope ratio mass spectrometer used for clumped isotope measurements in the Stable Isotope Laboratory at UEA. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
